
user-agent: ${spring.application.name}
nitter-status-api: https://status.d420.de/api/v1/instances
enable-health-check: false

spring:
  application:
    name: Nitter Load Balancer
  cloud:
    loadbalancer:
      health-check:
        path:
          # the key must be same as the service-id
          default: /elonmusk/rss
        repeat-health-check: false
        interval: 15m # not used when repeat-health-check is false
        refetch-instances: true # need this because our discovery client does not emit
        refetch-instances-interval: 15m
      retry:
        enabled: true
        retryable-status-codes: [500, 502, 503, 504, 404, 403, 429]