
perform-deep-check: true

logging:
  level:
    mikufan:
      cx: debug
    org:
      springframework:
        cloud:
          loadbalancer: debug
        web:
          client:
            RestTemplate: debug
    reactor:
      netty:
        http:
          client: debug
          client.HttpClientOperations: INFO